name: apk_ieee
description: "EcoGrid is a Flutter IoT application for ESP32 environmental monitoring, sensor visualization, and PDF/CSV reporting."
publish_to: 'none'
version: 0.1.2+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  http: ^1.5.0
  fl_chart: ^1.1.1
  google_fonts: ^6.1.0
  pdf: ^3.10.8
  printing: ^5.12.0
  flutter_svg: ^2.0.9

  dio: ^5.4.3
  path_provider: ^2.1.3
  open_file: ^3.3.2
  csv: ^6.0.0
  share_plus: ^7.2.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/sensor_dashboard/s_temp.png
    - assets/images/sensor_dashboard/s_humedad.png
    - assets/images/sensor_dashboard/s_ph.png
    - assets/images/sensor_dashboard/s_tds.png
    - assets/images/sensor_dashboard/s_uv.png

flutter_launcher_icons:
  android: true
  ios: true
  web: true
  windows: true
  macos: true
  image_path: "assets/icons/icono_app.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icono_app.jpeg"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
